Update org.eclipse.egit.github.core to 2.1.3
By updating to the latest org.eclipse.egit.github.core, it fix the following error:

Failed to execute goal com.github.github:downloads-maven-plugin:0.5:upload (default) on project h-ubu: Listing downloads failed: Missing or invalid User Agent string. See http://developer.github.com/v3/#user-agent-required (403) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.github:downloads-maven-plugin:0.5:upload (default) on project h-ubu: Listing downloads failed: Missing or invalid User Agent string. See http://developer.github.com/v3/#user-agent-required (403)

Signed-off-by: Clement Escoffier <clement.escoffier@gmail.com>